// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZsY5nXtl3i7iTKWFZcNPOzByBz4Rem0',
    appId: '1:943105972707:web:20c308cd82e5909e8228d6',
    messagingSenderId: '943105972707',
    projectId: 'sensorbase-80154',
    authDomain: 'sensorbase-80154.firebaseapp.com',
    databaseURL: 'https://sensorbase-80154-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensorbase-80154.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEdY2IBXOFm0DfC1wW6QkqG-qamvq7Pdg',
    appId: '1:943105972707:android:7be5161da42c86848228d6',
    messagingSenderId: '943105972707',
    projectId: 'sensorbase-80154',
    databaseURL: 'https://sensorbase-80154-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensorbase-80154.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCU0NaRx5DZf9da9CO-iOfm5xt7yyJUH4',
    appId: '1:943105972707:ios:26f9344f020ad6af8228d6',
    messagingSenderId: '943105972707',
    projectId: 'sensorbase-80154',
    databaseURL: 'https://sensorbase-80154-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensorbase-80154.appspot.com',
    iosBundleId: 'com.example.flfbSensor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCU0NaRx5DZf9da9CO-iOfm5xt7yyJUH4',
    appId: '1:943105972707:ios:26f9344f020ad6af8228d6',
    messagingSenderId: '943105972707',
    projectId: 'sensorbase-80154',
    databaseURL: 'https://sensorbase-80154-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensorbase-80154.appspot.com',
    iosBundleId: 'com.example.flfbSensor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXZsY5nXtl3i7iTKWFZcNPOzByBz4Rem0',
    appId: '1:943105972707:web:def0fcf6459cec528228d6',
    messagingSenderId: '943105972707',
    projectId: 'sensorbase-80154',
    authDomain: 'sensorbase-80154.firebaseapp.com',
    databaseURL: 'https://sensorbase-80154-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensorbase-80154.appspot.com',
  );
}
